name: campustrack
description: A Flutter app for Lost and Found Campus Tracking
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI utilities
  badges: ^3.1.2

  # State management
  provider: ^6.0.5

  # Firebase core & services - stable versions
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_messaging: ^14.9.4

  # Notifications
  flutter_local_notifications: ^17.2.4

  # Google Sign-In
  google_sign_in: ^6.2.1
  
  #flutter_secure_storage: ^9.0.0

  #shared_preferences: ^2.3.2

  # Image handling
  image_picker: ^0.8.6
  flutter_image_compress: ^2.2.0
  image: ^4.2.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.0
  js: ^0.6.7

  # ðŸ“Š Excel Export & File Management
  #excel: ^2.1.0
  syncfusion_flutter_xlsio: ^25.1.41
  path_provider: ^2.1.3
  permission_handler: ^11.3.0
  open_filex: ^4.5.0

  # ðŸ“¤ Sharing files
  share_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# Configuration for launcher icon
flutter_icons:
  android: true
  ios: true
  image_path: "assets/CampusTrackLogo.png"